application:
  name: demo
spring:
  profiles: default

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: avroautos
        output:
          destination: avroautos
        activitySink:
          destination: cartracker
        activitySource:
          destination: cartracker
        autos:
          group: spring
      kafka:
        binder:
          brokers: 192.168.99.100:9092
          zkNodes: 192.168.99.100:2181
          minPartitionCount: 1
          replicationFactor: 1
          autoCreateTopics: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
